### PR TITLE
Display execution command

### LINKED ISSUE #7: Aliases doesn't work with jbangdev/jbang-action@v0.35.0
I have the following configuration:

```yaml
      - name: Index Catalog
        uses: jbangdev/jbang-action@v0.35.0
        with:
          script: indexcatalog@quarkusio
          args: . ./app/registry.json

```

This is the error I get when Github runs it:

```
Run jbangdev/jbang-action@v0.35.0
  with:
    script: indexcatalog@quarkusio
    args: . ./app/registry.json
mkdir: cannot create directory ‘/github/home/.jbang’: Permission denied
[jbang] java.lang.RuntimeException: Invalid alias name ''
[jbang] Run with --verbose for more details

```

### PR DESCRIPTION
**Pull request by gastaldi**
Display the jbang execution line to allow easy copy/pasting

### CODE REVIEW

**Comment by maxandersen** [comment]
what do you have in your action to trigger a problem here ?

**Comment by maxandersen** [comment]
this fix breaks normal jbang usage of the docker image.

try

```
container-structure-test test --config container-structure-test.yaml -i jbang-action
```

**Comment by gastaldi** [comment]
This is what I have in my action: https://github.com/quarkusio/quarkus-extension-catalog/blob/57d34b08207669612cc210af800585b7cb58129d/.github/workflows/release.yml#L23

**Comment by gastaldi** [comment]
Ok, I am just echoing the execution line now

**Comment by gastaldi** [comment]
Superseded by https://github.com/jbangdev/jbang-action/pull/11

**Pull request closed without merging**
