### PR TITLE
fix: Run locally with 'act' fails (#28)

### PR DESCRIPTION
**Pull request by grumpyf0x48**
Use jbang full path to bypass 'act' issue with PATH environment variable

### CODE REVIEW

**Comment by maxandersen** [comment]
You want to make this PR against https://github.com/jbangdev/jbang/tree/main/src/jreleaser/distributions/jbang/docker as that is the source for this repo. I can do it but prefer if you do it so you get properly credited for it. let me know.

**Comment by grumpyf0x48** [comment]
OK, i will make a PR to jbang repo then.

So `jbangdev/jbang-action` is no longer used ?

**Comment by maxandersen** [comment]
It is. It's the repo the docker file is built from. 

The repo itself is though generated by jbang release process.

**Comment by grumpyf0x48** [comment]
@maxandersen, the changes of this PR have been merged so i can close the PR ?

**Comment by maxandersen** [comment]
Yes. Thanks!

**Pull request closed without merging**
